version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:ap-south-1:375530450530:task-definition/feature-toggle-task:14
        LoadBalancerInfo:
          ContainerName: feature-toggle-container
          ContainerPort: 5000


